### ISSUE TITLE
The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0

### ISSUE THREAD

**Issue by i400s** [espressif/esp-docs#12]
esp-idf is latest version (from today)
esp-docs is latest version (from today)

Directory structure:
esp/esp-idf
esp/esp-docs

Started idf environment using standard export.sh
Environment set up correctly. My project compiles. No issues.

Ran pip install esp-docs after starting esp-idf. Installed no issues.

Ran the following:
cd esp/esp-docs/examples/doxygen
./build_example.sh

Got a lot of errors. I'm guessing that is because the build is run multiple times for different languages and chips.

Ran a shortened version of the command contained in the ./build_example.sh file.

build-docs -l en -t esp32c6 --project-path src/
Which created the following output.

```
Will use 1 parallel builds and 1 jobs per build
[{'build_dir': '/mnt/md8/_development/esp/esp-docs/examples/doxygen/_build/en/esp32c6', 'source_dir': '/mnt/md8/_development/esp/esp-docs/examples/doxygen/en', 'language': 'en', 'target': 'esp32c6', 'sphinx_parallel_jobs': 1, 'builders': ['html'], 'input_docs': [''], 'doxyfile_dir': '.', 'project_path': 'src/'}]
Building in build_dir: /mnt/md8/_development/esp/esp-docs/examples/doxygen/_build/en/esp32c6
Running '/home/wilsonj/.espressif/python_env/idf5.3_py3.11_env/bin/python3 -u -m sphinx.cmd.build -j 1 -b html -d /mnt/md8/_development/esp/esp-docs/examples/doxygen/_build/en/esp32c6/doctrees -w sphinx-warning-log.txt -t esp32c6 -D idf_target=esp32c6 -D docs_to_build= -D config_dir=/home/wilsonj/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_docs -D doxyfile_dir=/mnt/md8/_development/esp/esp-docs/examples/doxygen -D project_path=/mnt/md8/_development/esp/esp-docs/examples/doxygen/src /mnt/md8/_development/esp/esp-docs/examples/doxygen/en /mnt/md8/_development/esp/esp-docs/examples/doxygen/_build/en/esp32c6/html'
en/esp32c6: Running Sphinx v4.5.0
en/esp32c6: Version: v1.4.0-62-gbea28a0074  Release: v1.4.0-62-gbea28a0074
en/esp32c6: fatal: no tag exactly matches 'bea28a0074c5169a5aed3edf4a518f9f4a1e2ef1'
en/esp32c6: Git commit ID:  bea28a0
en/esp32c6: loading translations [en]... done
en/esp32c6: 
en/esp32c6: Sphinx version error:
en/esp32c6: The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.
/mnt/md8/_development/esp/esp-docs/examples/doxygen/_build/en/esp32c6/doxygen-warning-log.txt not generated

en/esp32c6: Build failed due to new/different warnings (/mnt/md8/_development/esp/esp-docs/examples/doxygen/_build/en/esp32c6/sphinx-warning-log.txt):

en/esp32c6: 
en/esp32c6: Sphinx version error:
en/esp32c6: The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.

en/esp32c6: (Check files sphinx-known-warnings.txt and /mnt/md8/_development/esp/esp-docs/examples/doxygen/_build/en/esp32c6/sphinx-warning-log.txt for full details.)
[4]

The following language/target combinations failed to build:
language: en, target: esp32c6, errcode: 4

```
Without knowing how the program works exactly... I'm guessing that the "fatal: no tag exactly matches" error isn't that important and is related to git.

The actual bug, if I'm correct, is the "The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version".

I did try manually installing version 5, but then the program complained that its requirements were wrong and if I told the program to not check the requirements it also bailed with an error message.

This looks like its a similar bug to [https://github.com/googleapis/sphinx-docfx-yaml/issues/344](https://github.com/googleapis/sphinx-docfx-yaml/issues/344) but I have no idea how to resolve this which is why I'm creating this issue.

Thanks in advance for any help/resolution.

(Edited as the url https://github.com/googleapis/sphinx-docfx-yaml/issues/344 wasn't showing)

**Comment by ESP-Marius** [comment]
A new version of `sphinxcontrib.applehelp` was released (internal dependency of Sphinx), which do not support sphinx 4 which we currently used. esp-docs `1.7.2` will be available soon which pin these dependencies to the supported version, so hopefully that should fix your issue.

**Comment by i400s** [comment]
> A new version of `sphinxcontrib.applehelp` was released (internal dependency of Sphinx), which do not support sphinx 4 which we currently used. esp-docs `1.7.2` will be available soon which pin these dependencies to the supported version, so hopefully that should fix your issue.

Thank you very much for a quick response. I have just seen there is a new version on pypi so shall download and test that just as soon as I've had my first coffee of the day.

**Comment by i400s** [comment]
Have updated to the latest version. All is now working as it should be. Thank you, again, for a quick and speedy resolution.

**Comment by ESP-Marius** [comment]
> Have updated to the latest version. All is now working as it should be. Thank you, again, for a quick and speedy resolution.

Good to hear that it resolved your issue.
